NEDRC/Controllers/AdminController.cs
using NEDRC.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NEDRC.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext db;
        public AdminController()
        {
            db = new ApplicationDbContext();
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Details(string id)
        {
            return View(db.Users.Find(id));
        }
    }
}

NEDRC/Controllers/ReportController.cs
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNet.Identity;
using NEDRC.Models;
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NEDRC.ViewModel;

namespace NEDRC.Controllers
{
    public class ReportController : Controller
    {
        private readonly ApplicationDbContext db;

        public ReportController()
        {
            db = new ApplicationDbContext();
        }

        // GET: Report
        public ActionResult Index()
        {
            var reports = db.Reports.OrderBy(m => m.IsApproved);
            return View(reports.ToList());
        }

        public ActionResult Create()
        {
            var viewModel = new ReportViewModel
            {
                ApplicationUsers = db.Users.ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(Reports reports, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var reader = new System.IO.BinaryReader(upload.InputStream);
               
                var report = new Reports
                {
                    Name = reports.Name,
                    Date = DateTime.Now.ToShortDateString(),
                    IsApproved = reports.IsApproved,
                    Description = reports.Description,
                    Content = reader.ReadBytes(upload.ContentLength),
                    User = reports.User
                };
                db.Reports.Add(report);
                reader.Close();
                db.SaveChanges();
                RedirectToAction("Index");
            }
            
            return RedirectToAction("Index");
        }
        // GET: Reports/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reports reports = db.Reports.Find(id);
            if (reports == null)
            {
                return HttpNotFound();
            }
            return View(reports);
        }

        // POST: Reports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reports reports = db.Reports.Find(id);
            db.Reports.Remove(reports);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reports reports = db.Reports.Find(id);

            if (reports != null)
            {
                var content = reports.Content;

                return File(content, "application/pdf");
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
        }

        // GET: Reports/ApproveResult/5
        public ActionResult ApproveResult(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reports reports = db.Reports.Find(id);
            if (reports == null)
            {
                return HttpNotFound();
            }
            return View(reports);
        }

        [Route("Report/Approve/{id}/")]
        // POST: Reports/Approve/5
        [HttpPost, ActionName("Approve")]
        [ValidateAntiForgeryToken]
        public ActionResult Approve(int? id)
        {
            ApplicationUser users = db.Users.Find(User.Identity.GetUserId());
            Reports reports = db.Reports.Find(id);

            if (reports == null || users == null) return View();

            byte[] content = reports.Content;
            byte[] signature = users.Signature;

            iTextSharp.text.Image sigImg = iTextSharp.text.Image.GetInstance(signature);

            PdfReader reader = new PdfReader(content);
            using (MemoryStream ms = new MemoryStream())
            {
                try
                {
                    PdfStamper stamper = new PdfStamper(reader, ms);

                    sigImg.SetAbsolutePosition(450f, 80f);

                    sigImg.ScalePercent(25.0f); // 100.0f == same size


                    //Give some space after the image
                    sigImg.SpacingAfter = 1f;
                    sigImg.Alignment = Element.ALIGN_BOTTOM;

                    PdfContentByte over = stamper.GetOverContent(1);

                    over.AddImage(sigImg);

                    stamper.Close();

                    reports.Content = ms.ToArray();
                    content = reports.Content;

                    reports.IsApproved = true;

                    db.SaveChanges();

                    reader.Close();

                    return File(content, "application/pdf");
                }
                catch
                {
                    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
                }
            }
        }
    }
}

NEDRC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - North East Diagnostic and Research Centre</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBarView")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - North East Diagnostic and Research Centre</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NEDRC/Views/Shared/_NavBarView.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Report Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                @if (User.IsInRole("CanManageUsers"))
                {
                    <li>@Html.ActionLink("Manage Users","Index","Admin")</li>
                }
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("ManageReports","Index","Report")</li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>